### PR TITLE
fix tabela horario

### LINKED ISSUE #1043: Tabela Horária quebrada controlador "CONFIGURADO"
Depois que um controlador é finalizado (status alterado para `FINALIZADO`), a tabela horária quebra.
screen shot 2016-10-03 at 22 09 35

### PR DESCRIPTION
**Pull request by lesio**
close #1043

### CODE REVIEW

File: influunt-app/app/scripts/services/crud/influunt-alert.js [hunk 1]
```diff
@@ -54,7 +54,7 @@ angular.module('influuntApp')
 
       var promptPopup = function(title, text) {
         var defer = $q.defer(),
-            options = _merge(defaultOptions, {
+            options = _.merge(defaultOptions, {
```
Comment (ppires) [inline influunt-app/app/scripts/services/crud/influunt-alert.js]: 🌟 🌟 🌟 🌟 🌟 🌟 🌟
