### PR TITLE
fix layout upload dropzone

### LINKED ISSUE #451: Ajustes dropzone

### PR DESCRIPTION
**Pull request by leonardoherbert**
fix #451 #437 #438

### CODE REVIEW

File: influunt-app/app/scripts/directives/fake-dropzone-preview.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ angular.module('influuntApp')
...
+          var template = '<div class="dz-preview dz-processing dz-image-preview" data-anel-id="{{ data.idJsonAnel }}" data-imagem-id="{{ data.source }}"><div class="dz-details"><div class="dz-size" data-dz-size=""><strong>9.4</strong> KiB</div> <img data-dz-thumbnail="" alt="{{ data.nome }}" src="{{ data.source | imageSource }}"> </div><div class="dz-filename"><span data-dz-name="">{{ data.nome }}</span></div><div class="dz-success-mark"><span>✔</span></div><div class="dz-error-mark"><span>✘</span></div><div class="dz-error-message"><span data-dz-error-message=""></span></div></div>';
```
Comment (pauloFernandes) [inline influunt-app/app/scripts/directives/fake-dropzone-preview.js]: ⭐

File: influunt-app/app/styles/directives/dropzone.scss [hunk 2]
```diff
@@ -45,7 +45,15 @@
 
 .dropzone .dz-preview .dz-details img, .dropzone-previews .dz-preview .dz-details img {
   width: 100%;
-  height: auto;
+  height: 190px !important;
+}
+
+.dropzone .dz-filename span {
+  display: none;
+}
```
Comment (pauloFernandes) [inline influunt-app/app/styles/directives/dropzone.scss]: Sempre será display: none?

**Comment by pauloFernandes** [comment]
👍
